name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # ขั้นตอนเพิ่มพิเศษ: แก้ไขโครงสร้างไฟล์จาก Windows ให้เป็น Linux 
    - name: Fix gradlew line endings
      run: sed -i 's/\r$//' gradlew

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # สั่งคอมไพล์โปรเจกต์เป็นไฟล์ APK ออกมา
    - name: Build APK with Gradle
      run: ./gradlew assembleDebug

    # บันทึกไฟล์ APK ขึ้นเซิร์ฟเวอร์เพื่อให้กดดาวน์โหลดได้
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: opsu-apk-file
        path: "**/build/outputs/apk/debug/*.apk"
